### ISSUE TITLE
Archivespace Integration

### ISSUE THREAD

**Issue by carly322** [sourceryapp/sourcery-web-app#267]

**Comment by briankelleher** [comment]
- ArchiveSpace plugin - package for production
- ArchiveSpace plugin - finish repository documentation
- Public Documentation on Use
- Sourcery Web App - test error states (incorrect repository ID/org ID, long citation, etc)

**Comment by briankelleher** [comment]
- Flushed out documentation for [Local Development with ArchiveSpace](https://github.com/GreenhouseStudios/sourcery-web-app/wiki/ArchiveSpace---Local-Development).  I'm glad I did this because there were some interesting problems I ran into, trying a few methods.
    - This should cover a docker solution and running it with their local shell scripts.  Each has their own advantage, and it is really user preference.

**Comment by briankelleher** [comment]
https://github.com/GreenhouseStudios/sourcery-for-archivesspace

Repository updated for production use.
