### ISSUE TITLE
Outline Media Campaign for January Launch

### ISSUE THREAD

**Issue by foundhistory** [sourceryapp/sourcery-web-app#389]
Plan social media campaign for January / Build marketing assets (emails, flyers, social animations, etc.)

**Comment by bfoti** [comment]
(We need to figure out what to do with existing collateral)

**Comment by bfoti** [comment]
Add a list of web how-to videos to be recorded. (Voiceover sort of thing. Maybe use Scribe?)

**Comment by bfoti** [comment]
**Goals:**

- **Drive awareness & engagement from researchers** - basically, we want them to want to sign up for the app and place requests
- Drive more **buy-in from institutions** to want to offer Sourcery as a an official service
- Demonstrate to funders/stakeholders (Mellon Foundation, UConn, Corporation for Digital Scholarship) that we're doing a good job
- Remind people (especially librarians and archivists) that we are not out to steal their jobs - **building trust**. Remind them that we have had the dialogues with them, and we want to help them. This is a tool. 

Target Audiences - i.e. the people placing the requests, and the people fulfilling them.
- Humanities Researchers
- - Historians
- - Literature Scholars
- - Faculty
- - Graduate Students
- Institutions - can be the staff who are fulfilling requests (librarians and archivists), can also be the people who have decision-making power (administrators, leaders, etc.)
- - University Libraries
- - Archives
- - Town/City/Community Libraries/Historical Societies

Brooke - Find CCEI stuff & the report from the remote digital archives session that Garrett sessions.
