### ISSUE TITLE
Build list of proposal deadlines for 2024-2025 conferences

### ISSUE THREAD

**Issue by foundhistory** [sourceryapp/sourcery-web-app#395]

**Comment by ravenmariemorris** [comment]
[Proposal and Space Reservation Deadlines.docx](https://github.com/GreenhouseStudios/sourcery-web-app/files/13219176/Proposal.and.Space.Reservation.Deadlines.docx)

**Comment by ravenmariemorris** [comment]
The above attached document is a list of proposal and space reservation deadlines for conferences in 2024 and 2025.

**Comment by amabreeden** [comment]
https://docs.google.com/spreadsheets/d/1cAk7cBPTEOH2lf6H8OqrvbYj6OUU6d5TxZ8aEupCK0g/edit?usp=sharing WIP link for spreadsheet
