### ISSUE TITLE
Campaign planning: Outline content calendar

### ISSUE THREAD

**Issue by laurenharland** [sourceryapp/sourcery-web-app#408]

**Comment by bfoti** [comment]
### Strategy:
- How cryptic do we want to be?
- "Launching the service that will allow researchers to request documents from anywhere in the country." (Any library or archive). 
- The goal is to get as many researchers signed up for the app as possible. 
- "Any document. Anywhere." "Reach archivists all over the country through Sourcery." "Something's Brewing..."


### Timeline:
- **During November:** 
- - assess & update look of our social channels
- - Get the blog up and running (Brooke see if we can get it skinned). Archivespace blog post.
- - Create informational videos/animations of app features
- - Swag? Did Sara research T-shirts? Getting a booth at MLA? Booth materials from JMA? Lauren do some tshirt/hoodie mockups
- **Month of December: queue of teasers**
- - splash screen on the website teasing that an announcement is imminent; make cover photos on our channels match them
- - 6ish social teasers
- - Greenhouse Studios blog post, Sourcery blog post
- - Produce copy for home page (a banner?)
- - Come up with a giveaway idea/raffle for MLA
- **Tentative Launch Friday, January 5th**
- MLA: Jan Thur 4-Sun 7, Philadelphia (Tom going)
- AHA: Same time

**Comment by foundhistory** [comment]
Add e-mail campaign and blog post calendar to this plan
