### ISSUE TITLE
Draft update for "Roadmap" page for website

### ISSUE THREAD

**Issue by foundhistory** [sourceryapp/sourcery-web-app#413]

**Comment by ravenmariemorris** [comment]
[Sourcery Roadmap (Updated).docx](https://github.com/GreenhouseStudios/sourcery-web-app/files/12930234/Sourcery.Roadmap.Updated.docx)

**Comment by ravenmariemorris** [comment]
The document linked above is a draft for an updated roadmap for the Sourcery website.
